# Generated by Django 4.1 on 2022-08-17 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount2',
            fields=[
                ('id_bsch_2', models.SmallIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount4',
            fields=[
                ('id_bsch_4', models.AutoField(primary_key=True, serialize=False)),
                ('bsch_ch', models.SmallIntegerField()),
                ('id_bsch_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task2.bankaccount2')),
            ],
        ),
        migrations.CreateModel(
            name='ClassTable',
            fields=[
                ('id_class', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='OpeningBalance',
            fields=[
                ('id_bsch_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='task2.bankaccount4')),
                ('debit', models.FloatField()),
                ('credit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Turnover',
            fields=[
                ('id_bsch_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='task2.bankaccount4')),
                ('assets', models.FloatField()),
                ('liabilities', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='bankaccount2',
            name='id_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task2.classtable'),
        ),
    ]
